name: Vercel mini-app Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main
    paths:
      - "packages/mini-app/**"
  workflow_dispatch:

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.3.0
      
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.17
      
      # Cache dependencies
      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      
      # Cache Next.js build output
      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: packages/mini-app/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('packages/mini-app/package.json', 'bun.lockb') }}-${{ hashFiles('packages/mini-app/**/*.js', 'packages/mini-app/**/*.jsx', 'packages/mini-app/**/*.ts', 'packages/mini-app/**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('packages/mini-app/package.json', 'bun.lockb') }}-
            ${{ runner.os }}-nextjs-
      
      - name: Install dependencies
        run: bun install
      
      - name: Install Vercel CLI
        run: bun add -g vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
